### ISSUE TITLE
guildScheduledEvent issue

### ISSUE THREAD

**Issue by CrimsonTome** [hullcss/hullcss-discord-bot#4]
Lovely issue with the HullCSS bot when running on Freeside's Docker2 server

```
[root@docker2 ~]# docker logs hullcss 
HullCSS is online
/usr/hullcss/events/guildScheduledEvent.js:11
    .setFooter({text: `Created by ${guildScheduledEvent.creator.tag}`})
                                                                ^

TypeError: Cannot read properties of null (reading 'tag')
    at Client.<anonymous> (/usr/hullcss/events/guildScheduledEvent.js:11:65)
    at Client.emit (node:events:527:28)
    at GuildScheduledEventCreateAction.handle (/usr/hullcss/node_modules/discord.js/src/client/actions/GuildScheduledEventCreate.js:18:14)
    at Object.module.exports [as GUILD_SCHEDULED_EVENT_CREATE] (/usr/hullcss/node_modules/discord.js/src/client/websocket/handlers/GUILD_SCHEDULED_EVENT_CREATE.js:4:44)
    at WebSocketManager.handlePacket (/usr/hullcss/node_modules/discord.js/src/client/websocket/WebSocketManager.js:346:31)
    at WebSocketShard.onPacket (/usr/hullcss/node_modules/discord.js/src/client/websocket/WebSocketShard.js:482:22)
    at WebSocketShard.onMessage (/usr/hullcss/node_modules/discord.js/src/client/websocket/WebSocketShard.js:317:10)
    at WebSocket.onMessage (/usr/hullcss/node_modules/ws/lib/event-target.js:199:18)
    at WebSocket.emit (node:events:527:28)
    at Receiver.receiverOnMessage (/usr/hullcss/node_modules/ws/lib/websocket.js:1178:20)
    ``

**Comment by KieranRobson** [comment]
Fixed within https://github.com/hullcss/hullcss-discord-bot/commit/65a4f322c78b135066472f45163754dc0403380d
